function [data_info] = spike_sorting_params(data_info)

ratefilt_value = data_info.ratefilt_value;

    if strcmp(data_info.spikes_sorting, 'sorting') 

        data_info.params = Parameters.Dynamic(@Parameters.Config.BasicAnalysis,...
            'spk.type','sorted', ...
            'spk.ratefilt',ratefilt_value);
            %'dt.cacheread',false,...
        data_info.spikes = 'Sorted Spikes'; 

    elseif strcmp(data_info.spikes_sorting, 'sorting_noratefilt') 

        data_info.params = Parameters.Dynamic(@Parameters.Config.BasicAnalysis,...
            'spk.type','sorted', ...
            'spk.ratefilt',ratefilt_value,...
             'fr.min', -2);
            %'dt.cacheread',false,...
        data_info.spikes = 'Sorted noratefilt Spikes'; 
        
    elseif strcmp(data_info.spikes_sorting, 'sorting_aligned_thr_-3.5') 

        data_info.params = Parameters.Dynamic(@Parameters.Config.BasicAnalysis,...
            'spk.type','sorted', ...
            'spk.ratefilt',ratefilt_value,...
            'spk.threshold', -3.5);
            %'dt.cacheread',false,...
        data_info.spikes = 'Sorted Spikes aligned threshold -3.5'; 

    elseif strcmp(data_info.spikes_sorting, 'sorting_aligned_thr_-4.5') 

        data_info.params = Parameters.Dynamic(@Parameters.Config.BasicAnalysis,...
            'spk.type','sorted', ...
            'spk.ratefilt',ratefilt_value,...
            'spk.threshold', -4.5);
            %'dt.cacheread',false,...
        data_info.spikes = 'Sorted Spikes aligned threshold -4.5'; 

    elseif strcmp(data_info.spikes_sorting, 'sorting_aligned_thr_-4.5_noSmoothing') 

        data_info.params = Parameters.Dynamic(@Parameters.Config.BasicAnalysis,...
            'spk.type','sorted', ...
            'spk.ratefilt',ratefilt_value,...
            'spk.threshold', -4.5, ...
             'spk.smooth', 0);
            %'dt.cacheread',false,...
        data_info.spikes = 'Sorted Spikes aligned threshold -4.5'; 


    elseif strcmp(data_info.spikes_sorting, 'sorting_aligned_thr_-3') 

        data_info.params = Parameters.Dynamic(@Parameters.Config.BasicAnalysis,...
            'spk.type','sorted', ...
            'spk.ratefilt',ratefilt_value,...
            'spk.threshold', -3);
            %'dt.cacheread',false,...
        data_info.spikes = 'Sorted Spikes aligned threshold -3'; 

    elseif  strcmp(data_info.spikes_sorting, 'noisy')

        data_info.params = Parameters.Dynamic(@Parameters.Config.BasicAnalysis,... 
            'spk.type','sorted',...
            'spk.noise',true,...
            'spk.ratefilt',ratefilt_value); %,...
            %'dt.aligned', 'true');
            %'dt.cacheread',false,...

            %automatically alligned unless you specify "force_unaligned", 
            %and if there are two arrays recorded, it will give you unaligned 
            %unless you specify "force_aligned". 
        data_info.spikes = 'Noisy Spikes'; 

    elseif strcmp(data_info.spikes_sorting, 'unsorted')

         data_info.params = Parameters.Dynamic(@Parameters.Config.BasicAnalysis,...
             'spk.type', 'nev',...
              'dt.cacheread',false,...
             'spk.unsorted', true);
           %'dt.aligned', false,...

         data_info.spikes = 'Unsorted Data'; 

    elseif strcmp(data_info.spikes_sorting, 'unsorted_aligned')

         data_info.params = Parameters.Dynamic(@Parameters.Config.BasicAnalysis,...
             'spk.type', 'nev',...
             'spk.unsorted', true);

             %'dt.aligned', true,...

         data_info.spikes = 'Unsorted Data aligned'; 

    elseif strcmp(data_info.spikes_sorting, 'unsorted_aligned_noratefilt')

         data_info.params = Parameters.Dynamic(@Parameters.Config.BasicAnalysis,...
             'spk.type', 'nev',...
             'spk.unsorted', true,...
             'fr.min', -2, ...
             'spk.ratefilt', false);
             %'dt.aligned', true,...
         data_info.spikes = 'Unsorted Data aligned noratefilt'; 

    elseif strcmp(data_info.spikes_sorting, 'unsorted_aligned_noratefilt_4.5')

         data_info.params = Parameters.Dynamic(@Parameters.Config.BasicAnalysis,...
         'spk.type', 'nev',...
         'spk.unsorted', true,...
         'fr.min', -2, ...
         'spk.ratefilt', false, ...
         'spk.threshold', -4.5);
        disp('Threshold -4.5')
     data_info.spikes = 'Unsorted Data aligned noratefilt -4.5'; 

     elseif strcmp(data_info.spikes_sorting, 'unsorted_aligned_noratefilt_5.5')

         data_info.params = Parameters.Dynamic(@Parameters.Config.BasicAnalysis,...
         'spk.type', 'nev',...
         'spk.unsorted', true,...
         'fr.min', -2, ...
         'spk.ratefilt', false, ...
         'spk.threshold', -5.5);
        disp('Threshold -5.5')
     data_info.spikes = 'Unsorted Data aligned noratefilt -5.5'; 

     elseif strcmp(data_info.spikes_sorting, 'unsorted_aligned_noratefilt_3.5')

         data_info.params = Parameters.Dynamic(@Parameters.Config.BasicAnalysis,...
         'spk.type', 'nev',...
         'spk.unsorted', true,...
         'fr.min', -2, ...
         'spk.ratefilt', false, ...
         'spk.threshold', -4.5);
        disp('Threshold -4.5')
     data_info.spikes = 'Unsorted Data aligned noratefilt -4.5'; 



     elseif strcmp(data_info.spikes_sorting, 'sorting_aligned_noratefilt_4.5')

         data_info.params = Parameters.Dynamic(@Parameters.Config.BasicAnalysis,...
         'spk.type','sorted',...
         'fr.min', -2, ...
         'spk.ratefilt', false, ...
         'spk.threshold', -4.5);
        disp('Threshold -4.5')
     data_info.spikes = 'Unsorted Data aligned noratefilt -4.5'; 

    elseif strcmp(data_info.spikes_sorting, 'sorting_aligned_0.5filt_4.5')

         data_info.params = Parameters.Dynamic(@Parameters.Config.BasicAnalysis,...
         'spk.type','sorted',...
         'fr.min', 0.5, ...
         'spk.ratefilt', true, ... 
         'spk.threshold', -4.5);
        disp('Threshold -4.5')
     data_info.spikes = 'Unsorted Data aligned noratefilt -4.5'; 


     elseif strcmp(data_info.spikes_sorting, 'unsorted_aligned_thr_-4.5')

         data_info.params = Parameters.Dynamic(@Parameters.Config.BasicAnalysis,...
             'spk.type', 'nev',...
             'spk.unsorted', true,...\
             'spk.ratefilt', ratefilt_value,...
             'spk.threshold', -4.5);
              %'dt.aligned', true,...
              disp('Threshold -4.5')
         data_info.spikes = 'Unsorted Data aligned threshold -4.5';  

     elseif strcmp(data_info.spikes_sorting, 'unsorted_aligned_0_thr_-4.5')
         data_info.params = Parameters.Dynamic(@Parameters.Config.BasicAnalysis,...
             'spk.type', 'nev',...
             'spk.unsorted', true,...\
             'spk.ratefilt', ratefilt_value,...
             'spk.threshold', -4.5,...
              'dt.aligned', 0);
              disp('Threshold -4.5')
         data_info.spikes = 'Unsorted Data aligned threshold -4.5';  


    elseif strcmp(data_info.spikes_sorting, 'unsorted_aligned_thr_-3.5')

         data_info.params = Parameters.Dynamic(@Parameters.Config.BasicAnalysis,...
             'spk.type', 'nev',...
             'spk.unsorted', true,...\
             'spk.ratefilt', ratefilt_value,...
             'spk.threshold', -3.5);
              %'dt.aligned', true,...
              disp('Threshold -3.5')
         data_info.spikes = 'Unsorted Data aligned threshold -3.5'; 


    elseif strcmp(data_info.spikes_sorting, 'unsorted_aligned_thr_-4.0')

         data_info.params = Parameters.Dynamic(@Parameters.Config.BasicAnalysis,...
             'spk.type', 'nev',...
             'spk.unsorted', true,...
             'spk.ratefilt', ratefilt_value,...
             'spk.threshold', -4.0);
              %'dt.aligned', true,...
              disp('Threshold -4.0')

         data_info.spikes = 'Unsorted Data aligned threshold -4.0'; 

     elseif strcmp(data_info.spikes_sorting, 'unsorted_aligned_thr_-5.5')

         data_info.params = Parameters.Dynamic(@Parameters.Config.BasicAnalysis,...
             'spk.type', 'nev',...
             'spk.unsorted', true,...
             'spk.ratefilt', ratefilt_value,...
             'spk.threshold', -5.5);
              %'dt.aligned', true,...
              disp('Threshold -5.5')

         data_info.spikes = 'Unsorted Data aligned threshold -5.5'; 

    elseif strcmp(data_info.spikes_sorting, 'sorting_aligned_thr_-4.5_smoothed')
         data_info.params = Parameters.Dynamic(@Parameters.Config.BasicAnalysis,...
            'spk.type','sorted', ...
            'spk.ratefilt',ratefilt_value,...
            'spk.threshold', -4.5);

         data_info.params.spk.smoothparams.halfkernel = 0; %Go into Parameters.Config.BasicAnalysis for more info about kernel and smoothness
         data_info.params.spk.smoothparams.causal  = 0;
         data_info.spikes = 'Smoothed Spikes'; 

     elseif strcmp(data_info.spikes_sorting, 'smoothed')
         data_info.params = Parameters.Dynamic(@Parameters.Config.BasicAnalysis,...
            'spk.type','sorted', ...
            'spk.ratefilt',ratefilt_value );
         data_info.params.spk.smoothparams.halfkernel = 0; %Go into Parameters.Config.BasicAnalysis for more info about kernel and smoothness
         data_info.params.spk.smoothparams.causal  = 0;
         data_info.spikes = 'Smoothed Spikes'; 


    else

        error('Unknown sorting style - change spike sorting type variable')

    end
end

